### ISSUE TITLE
Remove a default `pr-comment` message from `communicate-on-pull-request-merged` 

### ISSUE THREAD

**Issue by mollyIV** [fastlane/github-actions#21]
Currently there is a default `pr-comment` message for `communicate-on-pull-request-merged` Action:

https://github.com/fastlane/github-actions/blob/e0ddd5315eab05c44d27678a99390780a5965d8f/communicate-on-pull-request-merged/action.yml#L8-L14

The message does not contain congrats for a pull request author. Below you will find an original message:

![image](https://user-images.githubusercontent.com/10795657/66842207-243c9500-ef6b-11e9-960d-af65628069bd.png)

To avoid ambiguity, we should delete a default message from an Action and make it `required` instead. 

The workflow file will look like this then:

```yaml
name: Processing merged pull requests
on: 
  pull_request:
    types: [closed]

jobs:   
  communicate-on-pr-merged:
    name: Communicate on pr merged
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: fastlane/github-actions/communicate-on-pull-request-merged@latest
      with:
        repo-token: "${{ secrets.BOT_TOKEN }}"
        pr-comment: "Hey @${{ github.event.pull_request.user.login }} :wave:\nThank you for your contribution to _fastlane_ and congrats on..."
```
